<a href="https://colab.research.google.com/github/TaillessTanuki/Intermediate-python/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np.__version__

'1.21.6'

# array

In [4]:
# python list cannot used arithmatic operation because it is not numeric
# so we use np.array()

a = [1,2,3,4,5]
b = [6,7,8,9,10]

numpy_a = np.array(a)
numpy_b = np.array(b)

In [5]:
print(numpy_a)
print(numpy_b)

print(numpy_a + numpy_b)
print(numpy_a * numpy_b)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[ 6 14 24 36 50]


In [9]:
print(type (a))
print(type (b))
print(type (numpy_a))
print(type (numpy_b))

<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
#print( a.shape) a list has no shape
#print(b.shape) b list has no shape
print(numpy_a.shape)
print(numpy_b.shape)

(5,)
(5,)


In [15]:
#print( a.shape) a list has no attribute size
#print(b.shape) a list has no attribute size
print(numpy_a.size)
print(numpy_b.size)

5
5


In [31]:
# 2D array
numpy_c = np.array(([1,2,3],[4,5,6]))
print(numpy_c)
print('---------------------')
print(type(numpy_c))
print('---------------------')
print(numpy_c.shape)
print('---------------------')
print(numpy_c.size)
print('---------------------')

[[1 2 3]
 [4 5 6]]
---------------------
<class 'numpy.ndarray'>
---------------------
(2, 3)
---------------------
6
---------------------


In [33]:
# 3D array
numpy_d = np.array(([[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]))
print(numpy_d)
print('---------------------')
print(type(numpy_d))
print('---------------------')
print(numpy_d.shape)
print('---------------------')
print(numpy_d.size)
print('---------------------')

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
---------------------
<class 'numpy.ndarray'>
---------------------
(2, 2, 3)
---------------------
12
---------------------


# array generating function

## matrix zeros or np.zeros()

In [19]:
#creating matrix zeros

zero_matrix = np.zeros(5)
print(zero_matrix)
print('---------------------')
zero_matrix2 = np.zeros((5,3))
print(zero_matrix2)

[0. 0. 0. 0. 0.]
---------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## matrix ones / 1 or np.ones()

In [34]:
#creating matrix ones

zero_matrix = np.ones(5)
print(zero_matrix)
print('---------------------')
zero_matrix2 = np.ones((5,3))
print(zero_matrix2)

[1. 1. 1. 1. 1.]
---------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## arange

In [21]:
# arange
f = np.arange(10)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
g = np.arange(10,20)
g

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
h = np.arange(10,20,2) #(start, finish, step)
h

array([10, 12, 14, 16, 18])

In [25]:
i = np.arange(-1,1,0.1)
i


array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])