<a href="https://colab.research.google.com/github/TaillessTanuki/Intermediate-python/blob/main/Numpy_Exercise_Lalu_Rizal_Pratama.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Exercise 1

### 1. create matrix from a list which has 4 rows and 3 columns

In [2]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
a.shape

(4, 3)

### 2. Create the following matrix 
[[2,7,12,0],
[3,9,3,4],
[4,0,1,3]]

In [4]:
b = np.array([[2,7,12,0],
              [3,9,3,4],
              [4,0,1,3]])
b

array([[ 2,  7, 12,  0],
       [ 3,  9,  3,  4],
       [ 4,  0,  1,  3]])

### 3. Create a 2D matrix with size of 10

In [5]:
c = np.array([0,1,2,3,4,5,6,7,8,9])
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
c.size

10

### 4. Create a 3D matrix of ones which has 2 rows, 3 columns, and 3 depth

In [9]:
d = np.array([[[1,2,3],
               [4,5,6],
               [13,14,15]],
              
              [[7,8,9],
               [10,11,12],
               [17,18,19]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [13, 14, 15]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [17, 18, 19]]])

In [10]:
d.shape

(2, 3, 3)

# Exercise 2

### 1. Generate a 1-D array containing 5 random integers from 0 to 100:

In [11]:
e = np.random.randint(0,100, size=5)
e

array([99, 25, 80, 13, 75])

### 2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100

In [13]:
f = np.random.randint(0,100,size = (3,5))
f

array([[89, 55, 18, 87, 12],
       [55, 88,  8, 62,  3],
       [83, 61,  0, 31, 19]])

### 3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [15]:
g = np.linspace(1.5, 5.5,30)
g

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])

# Exercise 3 

### 1. create a 3x3 matrix with values ranging from 2 to 10

In [19]:
h = np.arange(2,11).reshape(3,3)
h

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 2. concentenate the following arrays
####b [[0,1,3],[5,7,9]]
####c [[0,2,4],[6,8,10]]

In [22]:
i = np.array([[0,1,3],[5,7,9]])
j = np.array([[0,2,4],[6,8,10]])

print(i)
print('________________')
print(j)

[[0 1 3]
 [5 7 9]]
________________
[[ 0  2  4]
 [ 6  8 10]]


In [23]:
k = np.append(i,j, axis =0)
k

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [24]:
k = np.append(i,j, axis =1)
k

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

# Exercise 4

### 1. create a null vector / 1D array of size 10 and update fifth index to 11.

In [25]:
l = np.zeros(10)
l

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
l = np.append(l, 11)

In [31]:
l

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 11.])

### 2. Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [35]:
m = np.random.randint(0,100,size=(2,3))
m

array([[96, 73, 55],
       [69, 21, 68]])

In [36]:
m.reshape(3,2)

array([[96, 73],
       [55, 69],
       [21, 68]])

### 3. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

In [44]:
n = np.ones(16).reshape(4,4)
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
n[1:3,1:3]=0
n

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

### 4. Take a look at the following matrix. Access the [2, 1,1]

In [46]:
o = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])

In [48]:
o[2,1,1]

2

# Assignment

### 1. Create a 4x4 matrix with values ranging from 0 to 3.
(The following image is just as an example. It doesn't represent the real image of arrays in the question) 

In [61]:
x = np.random.randint(4, size=16).reshape(4,4)
x

array([[1, 3, 0, 1],
       [2, 2, 1, 0],
       [1, 2, 1, 0],
       [1, 0, 1, 0]])

### 2. Create an array with shape of 4x4 and turn it into two arrays along the second axis. (along second axis = on the column = horizontal

In [63]:
y = np.random.randint(10, size = 16).reshape(4,4)
y

array([[2, 0, 2, 5],
       [4, 7, 2, 8],
       [5, 5, 4, 7],
       [5, 6, 6, 9]])

In [67]:
new_arrays = np.hsplit(y,2)
new_arrays

[array([[2, 0],
        [4, 7],
        [5, 5],
        [5, 6]]), array([[2, 5],
        [2, 8],
        [4, 7],
        [6, 9]])]

In [68]:
z1 = new_arrays[0]
z2 = new_arrays[1]
print(z1)
print('--------')
print(z2)

[[2 0]
 [4 7]
 [5 5]
 [5 6]]
--------
[[2 5]
 [2 8]
 [4 7]
 [6 9]]
